In [1]:
# importing required libraries
import numpy as np
import pandas as pd
import plotly

In [2]:
# importing csv files as pandas dataframes
races = pd.read_csv("races.csv")
results = pd.read_csv("results.csv")
drivers = pd.read_csv("drivers.csv")
display(races)
display(results)
display(drivers)

raceId  year  round  circuitId                      name        date  \
0          1  2009      1          1     Australian Grand Prix  2009-03-29   
1          2  2009      2          2      Malaysian Grand Prix  2009-04-05   
2          3  2009      3         17        Chinese Grand Prix  2009-04-19   
3          4  2009      4          3        Bahrain Grand Prix  2009-04-26   
4          5  2009      5          4        Spanish Grand Prix  2009-05-10   
...      ...   ...    ...        ...                       ...         ...   
1074    1092  2022     18         22       Japanese Grand Prix  2022-10-09   
1075    1093  2022     19         69  United States Grand Prix  2022-10-23   
1076    1094  2022     20         32    Mexico City Grand Prix  2022-10-30   
1077    1095  2022     21         18      Brazilian Grand Prix  2022-11-13   
1078    1096  2022     22         24      Abu Dhabi Grand Prix  2022-11-20   

          time                                                url    fp1_date  \
0     06:00:00  http://en.wikipedia.org/wiki/2009_Australian_G...          \N   
1     09:00:00  http://en.wikipedia.org/wiki/2009_Malaysian_Gr...          \N   
2     07:00:00  http://en.wikipedia.org/wiki/2009_Chinese_Gran...          \N   
3     12:00:00  http://en.wikipedia.org/wiki/2009_Bahrain_Gran...          \N   
4     12:00:00  http://en.wikipedia.org/wiki/2009_Spanish_Gran...          \N   
...        ...                                                ...         ...   
1074  05:00:00  http://en.wikipedia.org/wiki/2022_Japanese_Gra...  2022-10-07   
1075  19:00:00  http://en.wikipedia.org/wiki/2022_United_State...  2022-10-21   
1076  20:00:00  http://en.wikipedia.org/wiki/2022_Mexican_Gran...  2022-10-28   
1077  18:00:00  http://en.wikipedia.org/wiki/2022_Brazilian_Gr...  2022-11-11   
1078  13:00:00  http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...  2022-11-18   

      fp1_time    fp2_date  fp2_time    fp3_date  fp3_time  quali_date  \
0           \N          \N        \N          \N        \N          \N   
1           \N          \N        \N          \N        \N          \N   
2           \N          \N        \N          \N        \N          \N   
3           \N          \N        \N          \N        \N          \N   
4           \N          \N        \N          \N        \N          \N   
...        ...         ...       ...         ...       ...         ...   
1074  04:00:00  2022-10-07  08:00:00  2022-10-08  04:00:00  2022-10-08   
1075  19:00:00  2022-10-21  22:00:00  2022-10-22  19:00:00  2022-10-22   
1076  18:00:00  2022-10-28  21:00:00  2022-10-29  17:00:00  2022-10-29   
1077  15:30:00  2022-11-12  15:30:00          \N        \N  2022-11-11   
1078  09:00:00  2022-11-18  12:00:00  2022-11-19  10:00:00  2022-11-19   

     quali_time sprint_date sprint_time  
0            \N          \N          \N  
1            \N          \N          \N  
2            \N          \N          \N  
3            \N          \N          \N  
4            \N          \N          \N  
...         ...         ...         ...  
1074   07:00:00          \N          \N  
1075   22:00:00          \N          \N  
1076   20:00:00          \N          \N  
1077   19:00:00  2022-11-12    19:30:00  
1078   13:00:00          \N          \N  

[1079 rows x 18 columns]

resultId  raceId  driverId  constructorId number  grid position  \
0             1      18         1              1     22     1        1   
1             2      18         2              2      3     5        2   
2             3      18         3              3      7     7        3   
3             4      18         4              4      5    11        4   
4             5      18         5              1     23     3        5   
...         ...     ...       ...            ...    ...   ...      ...   
25655     25661    1086       825            210     20    13       16   
25656     25662    1086       848              3     23    17       17   
25657     25663    1086       849              3      6    19       18   
25658     25664    1086       852            213     22    16       19   
25659     25665    1086       822             51     77     8       20   

      positionText  positionOrder  points  laps         time milliseconds  \
0                1              1    10.0    58  1:34:50.616      5690616   
1                2              2     8.0    58       +5.478      5696094   
2                3              3     6.0    58       +8.163      5698779   
3                4              4     5.0    58      +17.181      5707797   
4                5              5     4.0    58      +18.014      5708630   
...            ...            ...     ...   ...          ...          ...   
25655           16             16     0.0    69           \N           \N   
25656           17             17     0.0    69           \N           \N   
25657           18             18     0.0    69           \N           \N   
25658           19             19     0.0    68           \N           \N   
25659           20             20     0.0    65           \N           \N   

      fastestLap rank fastestLapTime fastestLapSpeed  statusId  
0             39    2       1:27.452         218.300         1  
1             41    3       1:27.739         217.586         1  
2             41    5       1:28.090         216.719         1  
3             58    7       1:28.603         215.464         1  
4             43    1       1:27.418         218.385         1  
...          ...  ...            ...             ...       ...  
25655         37   15       1:23.511         188.856        11  
25656         43   12       1:23.047         189.911        11  
25657         60    8       1:22.478         191.221        11  
25658         58   16       1:23.538         188.795        12  
25659         60   19       1:24.002         187.752       131  

[25660 rows x 18 columns]

driverId        driverRef number code  forename     surname         dob  \
0           1         hamilton     44  HAM     Lewis    Hamilton  1985-01-07   
1           2         heidfeld     \N  HEI      Nick    Heidfeld  1977-05-10   
2           3          rosberg      6  ROS      Nico     Rosberg  1985-06-27   
3           4           alonso     14  ALO  Fernando      Alonso  1981-07-29   
4           5       kovalainen     \N  KOV    Heikki  Kovalainen  1981-10-19   
..        ...              ...    ...  ...       ...         ...         ...   
849       851           aitken     89  AIT      Jack      Aitken  1995-09-23   
850       852          tsunoda     22  TSU      Yuki     Tsunoda  2000-05-11   
851       853          mazepin      9  MAZ    Nikita     Mazepin  1999-03-02   
852       854  mick_schumacher     47  MSC      Mick  Schumacher  1999-03-22   
853       855             zhou     24  ZHO    Guanyu        Zhou  1999-05-30   

    nationality                                             url  
0       British     http://en.wikipedia.org/wiki/Lewis_Hamilton  
1        German      http://en.wikipedia.org/wiki/Nick_Heidfeld  
2        German       http://en.wikipedia.org/wiki/Nico_Rosberg  
3       Spanish    http://en.wikipedia.org/wiki/Fernando_Alonso  
4       Finnish  http://en.wikipedia.org/wiki/Heikki_Kovalainen  
..          ...                                             ...  
849     British        http://en.wikipedia.org/wiki/Jack_Aitken  
850    Japanese       http://en.wikipedia.org/wiki/Yuki_Tsunoda  
851     Russian     http://en.wikipedia.org/wiki/Nikita_Mazepin  
852      German    http://en.wikipedia.org/wiki/Mick_Schumacher  
853     Chinese        http://en.wikipedia.org/wiki/Guanyu_Zhou  

[854 rows x 9 columns]

# Question 1
What are the maximum number of wins by a single driver during each F1 season?

In [3]:
# creating subsets of columns with the required columns
races_subset = races[['raceId', 'year']]
display(races_subset.raceId.unique())
display(races_subset.year.unique())

array([   1,    2,    3, ..., 1094, 1095, 1096], dtype=int64)

array([2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999,
       1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 2010, 1989,
       1988, 1987, 1986, 1985, 1984, 1983, 1982, 1981, 1980, 1979, 1978,
       1977, 1976, 1975, 1974, 1973, 1972, 1971, 1970, 1969, 1968, 1967,
       1966, 1965, 1964, 1963, 1962, 1961, 1960, 1959, 1958, 1957, 1956,
       1955, 1954, 1953, 1952, 1951, 1950, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022], dtype=int64)

In [4]:
# creating subsets of columns with the required columns
results_subset = results[['resultId','driverId','raceId','positionText']]
display(results_subset.resultId.unique())
display(results_subset.driverId.unique())
display(results_subset.raceId.unique())
display(results_subset.positionText.unique())

array([    1,     2,     3, ..., 25663, 25664, 25665], dtype=int64)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  56,  63,  62,  59,  66,  54,  55,  57,  58,  60,  61,  64,
        65,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 110, 109, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 135, 136, 137, 138, 139, 133, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 151, 149, 150, 152,  67, 153, 154, 155, 156, 157,
       158, 159, 163, 160, 161, 162, 164, 134, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

array([  18,   19,   20, ..., 1084, 1085, 1086], dtype=int64)

array(['1', '2', '3', '4', '5', '6', '7', '8', 'R', 'D', '9', '10', '11',
       '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', 'N',
       'W', 'F', 'E', '22', '23', '24', '25', '26', '27', '28', '29',
       '30', '31', '32', '33'], dtype=object)

In [5]:
# Cleaning result file 
results_cleaned=results_subset.loc[(results_subset['positionText'] != 'R') & (results_subset['positionText'] != 'N' )
                                       & (results_subset['positionText'] != 'E' ) & (results_subset['positionText'] != 'W' )& (results_subset['positionText'] != 'D')
                                                                                                                              & (results_subset['positionText'] != 'F' )]
display(results_cleaned.positionText.unique())

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33'],
      dtype=object)

In [6]:
# Converting Dtype Object -> int
results_cleaned = results_cleaned.astype({'positionText':'int'})
print(results_cleaned.dtypes)
display(results_cleaned.positionText.unique())

resultId        int64
driverId        int64
raceId          int64
positionText    int32
dtype: object


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [7]:
## creating subsets of columns with the required columns
drivers_subset = drivers[['driverId', 'forename','surname']]
display(drivers_subset.driverId.unique())
display(drivers_subset.forename.unique())
display(drivers_subset.surname.unique())

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

array(['Lewis', 'Nick', 'Nico', 'Fernando', 'Heikki', 'Kazuki',
       'Sébastien', 'Kimi', 'Robert', 'Timo', 'Takuma', 'Nelson',
       'Felipe', 'David', 'Jarno', 'Adrian', 'Mark', 'Jenson', 'Anthony',
       'Sebastian', 'Giancarlo', 'Rubens', 'Ralf', 'Vitantonio',
       'Alexander', 'Scott', 'Christijan', 'Markus', 'Sakon', 'Michael',
       'Juan', 'Christian', 'Tiago', 'Yuji', 'Jacques', 'Franck', 'Pedro',
       'Narain', 'Patrick', 'Ricardo', 'Antônio', 'Cristiano', 'Olivier',
       'Giorgio', 'Gianmaria', 'Zsolt', 'Marc', 'Heinz-Harald', 'Jos',
       'Justin', 'Ralph', 'Nicolas', 'Luciano', 'Jean', 'Eddie', 'Mika',
       'Tarso', 'Enrique', 'Gastón', 'Tomáš', 'Alex', 'Johnny', 'Allan',
       'Toranosuke', 'Luca', 'Alessandro', 'Damon', 'Stéphane', 'Esteban',
       'Shinji', 'Jan', 'Gerhard', 'Nicola', 'Ukyo', 'Vincenzo', 'Gianni',
       'Norberto', 'Martin', 'Andrea', 'Giovanni', 'Aguri', 'Taki',
       'Roberto', 'Karl', 'Bertrand', 'Domenico', 'Pierluigi', 'Nigel',
  

array(['Hamilton', 'Heidfeld', 'Rosberg', 'Alonso', 'Kovalainen',
       'Nakajima', 'Bourdais', 'Räikkönen', 'Kubica', 'Glock', 'Sato',
       'Piquet Jr.', 'Massa', 'Coulthard', 'Trulli', 'Sutil', 'Webber',
       'Button', 'Davidson', 'Vettel', 'Fisichella', 'Barrichello',
       'Schumacher', 'Liuzzi', 'Wurz', 'Speed', 'Albers', 'Winkelhock',
       'Yamamoto', 'Pablo Montoya', 'Klien', 'Monteiro', 'Ide',
       'Villeneuve', 'Montagny', 'de la Rosa', 'Doornbos', 'Karthikeyan',
       'Friesacher', 'Zonta', 'Pizzonia', 'da Matta', 'Panis', 'Pantano',
       'Bruni', 'Baumgartner', 'Gené', 'Frentzen', 'Verstappen', 'Wilson',
       'Firman', 'Kiesa', 'Burti', 'Alesi', 'Irvine', 'Häkkinen',
       'Marques', 'Bernoldi', 'Mazzacane', 'Enge', 'Yoong', 'Salo',
       'Diniz', 'Herbert', 'McNish', 'Buemi', 'Takagi', 'Badoer',
       'Zanardi', 'Hill', 'Sarrazin', 'Rosset', 'Tuero', 'Nakano',
       'Magnussen', 'Berger', 'Larini', 'Katayama', 'Sospiri',
       'Morbidelli', 'Fontana', 'L

In [8]:
## joining the 2 datasets to create a final database for analysis
Results_races_combined=pd.merge(results_cleaned,races_subset,on='raceId',how='left')
Final_Dataset=pd.merge(Results_races_combined,drivers_subset,on='driverId',how='left')
display(Final_Dataset)

resultId  driverId  raceId  positionText  year   forename     surname
0             1         1      18             1  2008      Lewis    Hamilton
1             2         2      18             2  2008       Nick    Heidfeld
2             3         3      18             3  2008       Nico     Rosberg
3             4         4      18             4  2008   Fernando      Alonso
4             5         5      18             5  2008     Heikki  Kovalainen
...         ...       ...     ...           ...   ...        ...         ...
14830     25661       825    1086            16  2022      Kevin   Magnussen
14831     25662       848    1086            17  2022  Alexander       Albon
14832     25663       849    1086            18  2022   Nicholas      Latifi
14833     25664       852    1086            19  2022       Yuki     Tsunoda
14834     25665       822    1086            20  2022   Valtteri      Bottas

[14835 rows x 7 columns]

In [9]:
# reading file and making subsets for the required columns
pd.set_option('mode.chained_assignment', None) # remove warnings
lap_times = pd.read_csv("lap_times.csv")
lap_times_subset = lap_times[['raceId','driverId', 'lap','milliseconds']]

In [10]:
# extracting the best driver based on the fastest lap time
pd.set_option('mode.chained_assignment', None) # remove warnings
lap_times_subset['rank'] = lap_times_subset.groupby(['raceId','driverId'])['milliseconds'].rank(method='first')
lap_times_filtered=lap_times_subset.loc[(lap_times_subset['rank'] == 1)]
lap_times_filtered

raceId  driverId  lap  milliseconds  rank
43         841        20   44         89844   1.0
98         841         1   41         90314   1.0
165        841        17   50         89600   1.0
228        841       808   55         90064   1.0
286        841        13   55         88947   1.0
...        ...       ...  ...           ...   ...
537877    1096       825   40         91158   1.0
537934    1096       848   40         89939   1.0
537968    1096       842   17         91018   1.0
538053    1096       849   45         90309   1.0
538110    1096       822   47         90352   1.0

[10146 rows x 5 columns]

In [11]:
# Filtering the Data to get only winners
Winners_data=Final_Dataset.loc[(Final_Dataset['positionText'] == 1)]
Winners_data = Winners_data.merge(lap_times_filtered, on=['raceId','driverId'], how='left')
display(Winners_data)

resultId  driverId  raceId  positionText  year forename     surname  \
0            1         1      18             1  2008    Lewis    Hamilton   
1           23         8      19             1  2008     Kimi   Räikkönen   
2           45        13      20             1  2008   Felipe       Massa   
3           67         8      21             1  2008     Kimi   Räikkönen   
4           89        13      22             1  2008   Felipe       Massa   
...        ...       ...     ...           ...   ...      ...         ...   
1068     25566       830    1082             1  2022      Max  Verstappen   
1069     25586       832    1083             1  2022   Carlos       Sainz   
1070     25606       844    1084             1  2022  Charles     Leclerc   
1071     25626       830    1085             1  2022      Max  Verstappen   
1072     25646       830    1086             1  2022      Max  Verstappen   

       lap  milliseconds  rank  
0     39.0       87452.0   1.0  
1     37.0       95405.0   1.0  
2     38.0       93600.0   1.0  
3     46.0       81670.0   1.0  
4     16.0       86666.0   1.0  
...    ...           ...   ...  
1068  64.0       75839.0   1.0  
1069  44.0       90813.0   1.0  
1070  62.0       67583.0   1.0  
1071  30.0       97491.0   1.0  
1072  45.0       82126.0   1.0  

[1073 rows x 10 columns]

In [12]:
# Filtering data from 1996 onwards,since we have data for lap times starting 1996 
average_lap_times = pd.DataFrame(Winners_data.groupby(['year','driverId'], as_index = False)['milliseconds'].mean())
average_lap_times=average_lap_times.loc[(average_lap_times['year'] >= 1996)]
average_lap_times

year  driverId   milliseconds
256  1996        30  101844.000000
257  1996        35   83689.500000
258  1996        44   85581.000000
259  1996        71   90738.000000
260  1997        14   88693.500000
..    ...       ...            ...
387  2021       839   81421.000000
388  2022       815   76028.000000
389  2022       830   88567.625000
390  2022       832   90813.000000
391  2022       844   80804.333333

[136 rows x 3 columns]

In [ ]:
# Summarizing data to get the number of win by each driver across all seasons
yearly_drivers_position = pd.DataFrame(Winners_data.groupby(['year','driverId'], as_index = False)['positionText'].count())
yearly_drivers_position=yearly_drivers_position.loc[(yearly_drivers_position['year'] >= 1996)]
yearly_drivers_position = yearly_drivers_position.rename(columns={'positionText':'races_won'})
display(yearly_drivers_position)
type(yearly_drivers_position)

In [14]:
## joining the 2 datasets to create a final database for analysis
yearly_drivers_position_lap=pd.merge(yearly_drivers_position,average_lap_times,on=['year','driverId'],how='left')
yearly_drivers_position_lap

year  driverId  races_won   milliseconds
0    1996        30          3  101844.000000
1    1996        35          4   83689.500000
2    1996        44          1   85581.000000
3    1996        71          8   90738.000000
4    1997        14          2   88693.500000
..    ...       ...        ...            ...
131  2021       839          1   81421.000000
132  2022       815          1   76028.000000
133  2022       830          8   88567.625000
134  2022       832          1   90813.000000
135  2022       844          3   80804.333333

[136 rows x 4 columns]

In [15]:
# filtering the data to only get the drivers with the maximum wins in a season
yearly_drivers_position_lap['count_max'] = yearly_drivers_position_lap.groupby(['year'])['races_won'].transform(max)
yearly_drivers_position2 = yearly_drivers_position_lap[(yearly_drivers_position_lap['races_won']==yearly_drivers_position_lap['count_max'])]
yearly_drivers_position2 = yearly_drivers_position2[['year','driverId','races_won','milliseconds']]
yearly_drivers_position2

year  driverId  races_won   milliseconds
3    1996        71          8   90738.000000
6    1997        35          7   80679.857143
12   1998        57          8   87343.625000
18   1999        57          5   85398.200000
22   2000        30          9   86048.111111
26   2001        30          9   87799.222222
32   2002        30         11   83060.727273
39   2003        30          6   76803.000000
44   2004        30         13   81564.076923
46   2005         4          7   86675.571429
47   2005         8          7   85411.571429
51   2006         4          7   83043.285714
55   2006        30          7   83434.000000
58   2007         8          6   86817.500000
65   2008        13          6   89610.166667
70   2009        18          6   87486.166667
74   2010         4          5   99307.800000
77   2010        20          5   93325.800000
82   2011        20         11   94468.272727
89   2012        20          5   99101.800000
95   2013        20         13   95295.230769
96   2014         1         11  100653.090909
99   2015         1         10   96220.700000
102  2016         1         10   85645.500000
106  2017         1          9   92422.000000
111  2018         1         11   89360.818182
116  2019         1         11   86550.727273
121  2020         1         11   84877.545455
130  2021       830         10   92733.800000
133  2022       830          8   88567.625000

In [16]:
# extracting the best driver based on the fastest lap time
yearly_drivers_position2['rank'] = yearly_drivers_position2.groupby('year')['milliseconds'].rank(method='first')
yearly_drivers_position2=yearly_drivers_position2.loc[(yearly_drivers_position2['rank'] == 1)]
yearly_drivers_position2

year  driverId  races_won   milliseconds  rank
3    1996        71          8   90738.000000   1.0
6    1997        35          7   80679.857143   1.0
12   1998        57          8   87343.625000   1.0
18   1999        57          5   85398.200000   1.0
22   2000        30          9   86048.111111   1.0
26   2001        30          9   87799.222222   1.0
32   2002        30         11   83060.727273   1.0
39   2003        30          6   76803.000000   1.0
44   2004        30         13   81564.076923   1.0
47   2005         8          7   85411.571429   1.0
51   2006         4          7   83043.285714   1.0
58   2007         8          6   86817.500000   1.0
65   2008        13          6   89610.166667   1.0
70   2009        18          6   87486.166667   1.0
77   2010        20          5   93325.800000   1.0
82   2011        20         11   94468.272727   1.0
89   2012        20          5   99101.800000   1.0
95   2013        20         13   95295.230769   1.0
96   2014         1         11  100653.090909   1.0
99   2015         1         10   96220.700000   1.0
102  2016         1         10   85645.500000   1.0
106  2017         1          9   92422.000000   1.0
111  2018         1         11   89360.818182   1.0
116  2019         1         11   86550.727273   1.0
121  2020         1         11   84877.545455   1.0
130  2021       830         10   92733.800000   1.0
133  2022       830          8   88567.625000   1.0

In [17]:
# joining the dataset to pull driver information into the final table
yearly_drivers_position3 = yearly_drivers_position2.merge(drivers_subset, on='driverId', how='left')
yearly_drivers_position3 = yearly_drivers_position3[['year','driverId','races_won','forename','surname']]
yearly_drivers_position3

year  driverId  races_won   forename     surname
0   1996        71          8      Damon        Hill
1   1997        35          7    Jacques  Villeneuve
2   1998        57          8       Mika    Häkkinen
3   1999        57          5       Mika    Häkkinen
4   2000        30          9    Michael  Schumacher
5   2001        30          9    Michael  Schumacher
6   2002        30         11    Michael  Schumacher
7   2003        30          6    Michael  Schumacher
8   2004        30         13    Michael  Schumacher
9   2005         8          7       Kimi   Räikkönen
10  2006         4          7   Fernando      Alonso
11  2007         8          6       Kimi   Räikkönen
12  2008        13          6     Felipe       Massa
13  2009        18          6     Jenson      Button
14  2010        20          5  Sebastian      Vettel
15  2011        20         11  Sebastian      Vettel
16  2012        20          5  Sebastian      Vettel
17  2013        20         13  Sebastian      Vettel
18  2014         1         11      Lewis    Hamilton
19  2015         1         10      Lewis    Hamilton
20  2016         1         10      Lewis    Hamilton
21  2017         1          9      Lewis    Hamilton
22  2018         1         11      Lewis    Hamilton
23  2019         1         11      Lewis    Hamilton
24  2020         1         11      Lewis    Hamilton
25  2021       830         10        Max  Verstappen
26  2022       830          8        Max  Verstappen

In [18]:
# converting year from integer -> string
yearly_drivers_position3['year'] = yearly_drivers_position3['year'].astype(str)
yearly_drivers_position3.dtypes

year         object
driverId      int64
races_won     int64
forename     object
surname      object
dtype: object

In [22]:
import plotly.express as px
fig = px.bar(yearly_drivers_position3, x="year", y="races_won",facet_row_spacing = 1,facet_col_spacing=1,title='Maximun number of races won by a single driver across seasons')
fig.update_traces(width=0.5)
fig.update_traces(marker_color='blue')
fig.show()